#!/usr/bin/env python
'''
Autogenerated code using arya.py
Original Object Document Input: 
{"infraRsDomP":{"attributes":{"tDn":"uni/phys-tenant_1_bm_domain","status":"created"},"children":[]}}
'''

# list of packages that should be imported for this code to work
import cobra.mit.access
import cobra.mit.request
import cobra.mit.session
import cobra.model.infra
from cobra.internal.codec.xmlcodec import toXMLStr

# log into an APIC and create a directory object
ls = cobra.mit.session.LoginSession('https://ssacimn010a02apic01.ss.astontech.com', 'admin', 'amkunn4D')
md = cobra.mit.access.MoDirectory(ls)
md.login()

# the top level object on which operations will be made
# Replace the text below with the dn of your top object
topMo = md.lookupByDn('uni/infra/attentp-test_phys_aep')

# build the request using cobra syntax
infraRsDomP = cobra.model.infra.RsDomP(topMo, tDn=u'uni/phys-tenant_1_bm_domain')


# commit the generated code to APIC
print toXMLStr(topMo)
c = cobra.mit.request.ConfigRequest()
c.addMo(topMo)
md.commit(c)

